### ISSUE TITLE
The portalEl is useful to apply the same css hierarchy as the zoomed element

### ISSUE THREAD

**Issue by hardchiu** [rpearce/image-zoom#263]
The commit 03be3b6f2ee831f07fe2645326eba89bb1bbc22e removed portalEl. Actually that config is useful in my case.

## Expected behavior
I expected the zoomed element will apply the same css class before / after zooming. i.e. There are some css class set in the portalEl.

## Actual behavior
The zoomed modal is directly under document.body, which we are unable to set any css class to it.

## Alternative
Another option is to provide css class config to the modal, but having a portalEl allow applying the same css hierarchy.

## Workaround
We will stay at 5.0.0-alpha-8 which the portalEl is still available.

**Comment by rpearce** [comment]
@hardchiu Thanks for your issue, and I will keep this in mind.

Version 5 took a hard nose-dive after some implementation details came up that were impossible to work around. I'll need to redo this a slightly different way (I already know what I'm going to do).

I'm on parental leave from work and am not working on it right now but will return.

**Comment by rpearce** [comment]
@hardchiu What is an example `portalEl` that you are using? Is it just a `<div>` at the end of the body that you can control?

I removed `portalEl` because I wasn't sure I could support zooming the image in any arbitrary place in the DOM. That doesn't mean I was right, though.

**Comment by rpearce** [comment]
Now you've got me back thinking about getting this release out again. I'll get back on it.

**Comment by hardchiu** [comment]
For example we wish to zoom an element in the following structure
```
<div class="a">
  <div class="someOtherStuff">...</div>
  <div class="b">
    <img class="c"/>
  </div>
</div>
```

We may be already using css class like ".a .b .c" to style the image.

To apply the same css class to the zoomed element, we may do it in two ways with the portalEl:

## 1. Put the portalEl under the same parent node of the zooming target
```
<div class="a">
  <div class="someOtherStuff">...</div>
  <div class="b">
    <div class="portal"></div>
    <img class="c"/>
  </div>
</div>
```
where portal is position absolute or fixed to fill all the screen spaces. Note css class ".a .b .c" also apply to the zoomed image under the portal.

## 2. Put the portalEl in a separate branch
```
<div class="a">
  <div class="someOtherStuff">...</div>
  <div class="b">
    <img class="c"/>
  </div>
</div>
<div class="a">
  <div class="b">
    <div class="portal"></div>
  </div>
</div>
```
The new branch has no other content so it can be easily filling up the whole screen.
Note css class ".a .b .c" also apply to the zoomed image under the portal.

If we are able to set the portalEl, we can fix it with different structure (which keep the full screen) in different cases.
i.e. It would be the user's responsibility to supply a usable portalEl if they provide that config.

**Comment by rpearce** [comment]
The issue with putting the `portalEl` anywhere _except_ at the end of `document.body` is that – even if it is `fixed` – you will run into problems across all major browsers with regard to positioning if there is a `translate3d` or `translateZ` or `overflow: hidden` anywhere in the parent (the styling and animations will completely break because you can't have `fixed` elements in these scenarios that work all the time).

There are data attributes that can be used for CSS styling, like `data-rmiz-modal-content` in version 4, that would allow you to style it further if you needed to. For example:

```css
[data-rmiz-modal-content] {
  /* code here... */
}
```

I'll keep thinking and working.

**Comment by hardchiu** [comment]
There are cases that will not work if the portalEl is not put directly under document.body, but there are other cases or workaround that can make it work (not every case need to use position fixed).

That's why I said it would become the users' responsibility to supply a usable portalEl if they provide that config.

Are you mean to use data-rmiz-modal-content as selector for styling in css?

Actually it is not about how to style the the zoomed element. The aim of keeping the hierarchy is to avoid duplicate the same set of style to the zoomed element.

I am not sure if it is usual to expect the zoomed element automatically applying the same css as the original targeted element. 
In my case, I think it would be easier for me to keep the original css selector working instead of duplicate a set of style to the zoomed element (since there are many different targets).

Thanks for considering, let me know if you need more elaboration of my case.

**Comment by rpearce** [comment]
Overall, a modal at the end of the `body` must be used to meet accessibility standards, so I believe that providing a `portalEl` would hurt accessibility. There is a lot to this.

* * *

> (not every case need to use position fixed)

That's true. I'll consider `position: absolute;` again as I work on the next version.

> Are you mean to use data-rmiz-modal-content as selector for styling in css?

The data selectors offer a way of styling modal-related elements.

**Comment by hardchiu** [comment]
Are both the options I mentioned above unable to meet accessibility standards?

I am wonder if the option 2 above is still able to meet, since that is a new branch created at the end of the `body` to hold the `portalEl` (i.e. no other content beside the `portalEl` node.)

If the `portalEl` need to be strictly under `body`, having a `zoomImgWrapperEl` render prop would help.

```
zoomImgWrapperEl: ({ children }) => ReactNode.
```
It allow user to adjust the structure between `data-rmiz-overlay` and `data-rmiz-zoomed`.


Maybe I better specify the case instead of trying to comment on the interface, since you know the underlying constrain better.

The rationale behind this issue is that elements/components can be in different style under different container, and the stylesheet can be an external theme. It would be better if we don't need to flatten the style and duplicate the rules for the zoomed element.
(It is like providing a way to setup the theme for the modal)

**Comment by rpearce** [comment]
@hardchiu

Regarding accessibility, there are roles and other elements that need to be present in order to keep focus in the modal for screen readers in addition to hiding other elements in the background so that they are not readable when the modal dialog is open. Doing this and making the image zoom to its specified dimensions means that including other wrapper elements won't work for images, which is what _this_ library was about until recently... read below.

In version 4 of this project, you can zoom _anything_, including a `<div>` , as your second thing suggests. It turns out that this was not necessarily a good thing to include in an _image_ zoom library, for it makes things fairly complicated.

I'm currently working on rewriting everything again, so I will keep this in mind, but I don't yet see the value in zooming `<div>`s around an image when the image is what we want to zoom. Can you explain why you would want to do that?

**Comment by rpearce** [comment]
Update on v5 FYI: https://github.com/rpearce/image-zoom/discussions/274

**Comment by rpearce** [comment]
I'm going to close this, for copying a collection of elements' CSS over isn't a direction I think we should go here.
